spring.application.name=MagicFridgeAI

#Configure datasource of H2

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

#Configure JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.h2.console.enable=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Configure Flyway
spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
